### ISSUE TITLE
First release to-do list

### ISSUE THREAD

**Issue by d10sfan** [d10sfan/cat-fish#3]
- [x] create readme & license
- [x] add help popup with license info (and my game info at the top)
- [x] fix clear color
- [x] look at path 2d smoother project
- [x] add camera similar to tower defense one or have a long track to the right to fill in
- [x] add cat meow when clicked
- [x] sound effect when you click a fish, blended
- [x] test on mobile
- [x] upload to itch.io and test on github
